Ekart_prj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import HomeView,ItemDetailView,CheckOutView,add_to_cart,\
    remove_from_cart,order_summary,increase_quantity,decrease_quantity,\
    remove_from_order_summary,cat_filter,PaymentView,add_coupon_view,\
    Request_RefundView,MyOrders
app_name='core'

urlpatterns=[
    path('',HomeView.as_view(), name='home'),
    path('catogory/<slug>/',cat_filter, name='catagory-filter'),
    path('product/<slug>/',ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/',add_to_cart,name='add-to-cart'),
    path('buy_now/<slug>/',add_to_cart,name='buy-now'),
    path('remove-from-cart/<slug>/',remove_from_cart,name='remove-from-cart'),
    path('order_summary/',order_summary.as_view(),name='order-summary'),
    path('increase-quantity/<slug>/',increase_quantity,name='increase-quantity'),
    path('decrease-quantity/<slug>/',decrease_quantity,name='decrease-quantity'),
    path('remove_from_order_summary/<id>/',remove_from_order_summary,name='remove-item-from-summary'),
    path('checkout/',CheckOutView.as_view(), name='checkout'),
    path('coupon/',add_coupon_view, name='coupon'),
    path('payment/<payment_option>/',PaymentView.as_view(), name='payment'),
    path('refund-request',Request_RefundView.as_view(),name='refund-request'),
    path('myorders',MyOrders,name='myorders')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    {% block title %}
  <title>Home</title>
    {% endblock %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href={% static "css/bootstrap.min.css" %} rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href={% static "css/mdb.min.css" %} rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href={% static "css/style.min.css" %} rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
{% block extra_head %}
{% endblock extra_head %}
  </style>
<link rel="stylesheet" href="{% static 'fk1.css' %}" />
		<link rel="stylesheet" href="{% static 'fk2.css' %}" />
<link rel="stylesheet" href="{% static 'fk3.css' %}" />
</head>

{% include 'navbar1.html' %}

<body>

<div class="mt-5 pt-4">
    {% if messages %}

    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
  <strong class="font-weight-bold">{{ message }}</strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
    {% endfor %}
{% endif %}
</div>
</div>
{% block content %}
{% endblock %}
{% include 'footer.html' %}

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
{% block extra_scripts %}
{% endblock extra_scripts %}
</body>

</html>

templates/footer.html
<div class="mt-5 pt-4">
    <footer class="page-footer text-center
    font-small mt-4 wow fadeIn fixed-bottom">

        <!--Copyright-->
        <div class="footer-copyright py-3">
            © 2020 Copyright:
            <a href="#" target="_blank"> Yogi e-kart </a>
        </div>
        <!--/.Copyright-->

    </footer>
</div>

templates/home.html
{% extends 'base.html' %}
{% block content %}
    {% load add_to_cart %}
    <!--Main layout-->
    <main>
        <div class="container">

            <!--Navbar-->
            <nav class="navbar navbar-expand-sm navbar-dark mdb-color lighten-3 mt-3 mb-5">

                <!-- Navbar brand -->
                <span class="navbar-brand">Categories:</span>

                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">

                    <!-- Links -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'core:home' %}">All
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:catagory-filter' 'cl' %}">Clothes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:catagory-filter' 'fw' %}">Foot wears</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:catagory-filter' 'w' %}">Watches</a>
                        </li>

                    </ul>
                    <!-- Links -->

                    <form class="form-inline" method="POST" action=".">
                        {% csrf_token %}
                        <div class="md-form my-0">
                            <input class="form-control mr-sm-2" type="text"
                                   placeholder="Search" name="search_text" aria-label="Search">
                        </div>
                        <button type="submit"><i class="fas fa-search"></i></button>
                    </form>
                </div>
                <!-- Collapsible content -->

            </nav>
            <!--/.Navbar-->

            <!--Section: Products v.3-->
            <section class="text-center">

                <!--Grid row-->
                <div class="row">

                    {% for i in object_list %}
                        <!--Grid column-->
                        {#          <div class="col-lg-3 col-md-6 mb-4">#}

                        <div class="_3liAhj" style="margin: auto">
                            <a class="Zhf2z-" target="_blank" href="{{ i.get_absolute_url }}">
                                <div>
                                    <div>
                                        <div class="_3BTv9X" style="height: 280px; width: 200px;">
                                            <img class="_1Nyybr  _30XEf0"
                                                 src="{{ i.image.url }}">
                                        </div>
                                    </div>
                                </div>
                            </a>

                            <a class="_2cLu-l blue-text" target="_blank" href="{{ i.get_absolute_url }}">
                                <h6>{{ i.title }}</h6></a>

                            <a class="_1Vfi6u" target="_blank" href="{{ i.get_absolute_url }}">
                                <div class="_1uv9Cb">

                                    {% if i.discount_percent %}
                                    <div class="_3auQ3N font-weight-bold">{{ i.price }}</div>
                                    <div class="VGWI6T">
                                        <span>{{ i.discount_percent }}% off</span>
                                    </div>
                                    <h4 class="font-weight-bold blue-text">
                                    <strong>Rs.{{ i.offer_url }}</strong>
                                </h4>
                                    {% else %}
                                    <h4 class="font-weight-bold blue-text">
                                    <strong>Rs.{{ i.price }}</strong>
                                    </h4>
                                    {% endif %}
                                </div>


                            </a>
                        </div>
                    {% endfor %}
                </div>
            </section>
            <!--Section: Products v.3-->

            {% if is_paginated %}
            <nav class="d-flex justify-content-center wow fadeIn">
                <ul class="pagination pg-blue">

                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    {% endif %}
                    <li class="page-item active">
                        <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                        {% endif %}
                </ul>
            </nav>
            {% endif %}

        </div>
    </main>
    <!--Main layout-->

{% endblock %}

templates/myorders.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h3>My Orders</h3>
    <div class="table-responsive text-nowrap white">
    <table class="table table-responsive-md text-center table-bordered">
    <thead class="table-dark">
        <tr>
            <th>#</th>
            <th>Ref Code</th>
            <th>Title</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Ordered Date</th>
            <th>Delivery Status</th>
        </tr>
    </thead>
    <tbody>
        {% for myorder in myorders %}
            <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ myorder.ref_code }}</td>
                {% for i in myorder.items.all %}
            <td>{{ i.item.title }}</td>
            <td>{{ i.quantity }}</td>
            <td>{% if i.item.discount_percent %}
                            {{ i.get_total_price }}
                            <span class="badge badge-primary">saving Rs.{{ i.total_saving }}</span>
                            {% else %}
                            {{ i.get_total_price }}
            {% endif %}</td>
                    {% endfor %}
            <td>{{ myorder.ordered_date }}</td>
            {% ifequal myorder.recieved True %}
            <td>Delivered</td>
            {% else %}
            <td>Pending</td>
            {% endifequal %}
            </tr>
        {% endfor %}
    </tbody>
    </table>
    </div>

    </div>

{% endblock %}

templates/navbar1.html
{% load static %}
{% load add_to_cart %}

<div class="container">
<div class="row">
<div class="col-md-12">
{#<nav class="navbar navbar-expand-lg navbar-light bg-light">#}
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
  <a class="navbar-brand" href="/">
      <strong class="pink-text shadow" style="font-style: italic;font-family: 'Arial Black'">YOGI e-kart</strong>
  </a>
<a style="margin-left: 29%;">
  <a class="navbar-brand" href="{% url 'core:order-summary' %}">
      {% if request.user.is_authenticated %}
        <span class="badge red z-depth-1"> {{ request.user|cart_item_count }} </span>
        {% endif %}
  <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
      </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
      {% if request.user.is_authenticated %}
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link">Hello! {{ user.first_name|capfirst }} <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:myorders' %}">My Orders</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account_logout' %}">LogOut</a>
      </li>
        {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'account_signup' %}">Signup</a>
        </li>
    </ul>
      {% endif %}
  </div>
</a>
</nav>
</div>
</div>
</div>

templates/order_summary.html
{% extends 'base.html' %}
{% block title %}<title>Yogi e-kart - Cart Summary</title>{% endblock %}
{% block content %}
    <div class="container">
        <div class="table-responsive text-nowrap white">
            <table class="table table-responsive-md">
                <thead>
                <tr>
                    <th class="font-weight-bold">#</th>
                    <th class="font-weight-bold">Title</th>
                    <th class="font-weight-bold">Price</th>
                    <th class="font-weight-bold">Quantity</th>
                    <th class="font-weight-bold">Total Price</th>
                </tr>
                </thead>
                <tbody>
                {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row">
                            <a href="{% url 'core:product' order_item.item.slug %}"
                               class="hoverable blue-text font-weight-bold">
                            {{ forloop.counter }}
                            </a>
                        </th>
                        <td>
                            <a href="{% url 'core:product' order_item.item.slug %}"
                               class="hoverable blue-text font-weight-bold">
                        {{ order_item.item.title }}
                        </a>
                        </td>
                        <td>{{ order_item.item.offer_url }}</td>
                        <td>
                        <div class="_3RkJty">
                                <div class="_3md1dr">

                                <a href="{% url 'core:decrease-quantity' order_item.item.slug %}">

                                <button class="wNrY5O">–</button>
                                </a>
{#                                    <span class="badge bg-info ml-2 mr-2">{{ order_item.quantity }}</span>#}
                                <button class="wNrY5O mr-2 ml-2">{{ order_item.quantity }}</button>
                                    <a href="{% url 'core:increase-quantity' order_item.item.slug %}">

                            <button class="wNrY5O"> +</button>
                            </a>
                                </div>
                        </div>
                        </td>
                        <td>
                            {% if order_item.item.discount_percent %}
                            {{ order_item.get_total_price }}
                            <span class="badge badge-primary">saving Rs.{{ order_item.total_saving }}</span>
                            {% else %}
                            {{ order_item.get_total_price }}
                            {% endif %}
                        </td>
                        <td><a href="{% url 'core:remove-item-from-summary' order_item.id %}" style="color: red">
                            <i class="fas fa-trash"></i></a></td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4" class="font-weight-bold text-center">Your cart is empty</td>
                    </tr>
                    <td>
                    <td colspan="4">
                        <a href="/">
                            <button class="btn btn-default float-right">Continue Shopping</button>
                        </a>
                    </td>
                    <tr>

                    </tr>
                {% endfor %}
                {% if object.grand_total_price %}
                    <tr>
                        <td colspan="4" class="font-weight-bold text-center">Order Total</td>
                        <td class="font-weight-bold">Rs.{{ object.grand_total_price }}</td>
                    </tr>
                    <tr>
                        <td colspan="5">
                            <a class='btn btn-warning float-right ml-2' href='{% url 'core:checkout' %}'>Proceed to
                                checkout</a>
                            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                        </td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/payment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <title>Yogi e-kart - Payment</title>
{% endblock %}
{% block extra_head %}

{#<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" type="text/css" rel="stylesheet">#}
<style media="screen">

#stripe-label {
  font-family: "Helvetica Neue", Helvetica, sans-serif;
  font-size: 16px;
  font-variant: normal;
  padding: 0;
  margin: 0;
  -webkit-font-smoothing: antialiased;
}

#stripe-button {
  border: none;
  border-radius: 4px;
  outline: none;
  text-decoration: none;
  color: #fff;
  background: #32325d;
  white-space: nowrap;
  display: inline-block;
  height: 40px;
  line-height: 40px;
  padding: 0 14px;
  box-shadow: 0 4px 6px rgba(50, 50, 93, .11), 0 1px 3px rgba(0, 0, 0, .08);
  border-radius: 4px;
  font-size: 15px;
  font-weight: 600;
  letter-spacing: 0.025em;
  text-decoration: none;
  -webkit-transition: all 150ms ease;
  transition: all 150ms ease;
  float: left;
  margin-left: 12px;
  margin-top: 28px;
}

button:hover {
  transform: translateY(-1px);
  box-shadow: 0 7px 14px rgba(50, 50, 93, .10), 0 3px 6px rgba(0, 0, 0, .08);
  background-color: #43458b;
}

#stripe-form {
  padding-top: 30px;
  height: 120px;
}

label {
  font-weight: 500;
  font-size: 14px;
  display: block;
  margin-bottom: 8px;
}

#card-errors {
  height: 20px;
  padding: 4px 0;
  color: #fa755a;
}

.stripe_form-row {
  {#width: 70%;#}
  {#float: left;#}
}



/**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;
}
</style>
{% endblock extra_head %}

{% block content %}

    <div class="container-fluid">

      <!-- Heading -->
      <h2 class="h2 text-center">Payment</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->

        <!--Grid column-->
        {% if order.shipping_address %}
            <div class="col-md-12 mb-4">
            <h5 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">Your orders will deliver to below address:</span></h5>

          <ul class="list-group p-3 bg-white z-depth-1">
          {% for i in address %}

              <li>
                  <h6>{{ i|capfirst }}</h6>
              </li>
          {% endfor %}
          </ul>
        </div>
        {% endif %}
        <!--Grid column-->
        <div class="col-md-12 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">{{order.items.count}}</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
              {% for i in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ i.quantity }} x {{ i.item.title }}</h6>
                <small class="text-muted">{{ i.item.description|truncatewords:20 }}</small>
              </div>
              <span class="text-muted">{{ i.get_total_price }}</span>
            </li>
              {% endfor %}
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{order.coupon.code}}</small>
              </div>
              <span class="text-success">-Rs.{{ order.coupon.coupon_amount }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (INR)</span>
              <strong>Rs.{{ order.coupon_disc_total }}</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
        {% ifequal order.coupon None %}
          <form class="card p-2" method="post" action="{% url 'core:coupon' %}">
              {% csrf_token %}
            <div class="input-group">
                {{ coupon_form.code }}
{#              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">#}
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
              </div>
            </div>
          </form>
        {% endifequal %}
          <!-- Promo code -->

        </div>
        <!--Grid column-->
      <div class="col-md-12 mb-5 pb-4">

        <h6 class="grey-text">Note:for testing card no.:4242 4242 4242 4242...</h6>
          <!--Card-->
          <div class="card">
                   <script src="https://js.stripe.com/v3/"></script>
                  <form action="." method="post" id="stripe-form">
                      {% csrf_token %}
                      <div class="stripe_form-row col">
                          <label for="card-element" id="stripe-label">
                              Credit or debit card
                          </label>
                          <div id="card-element" class="StripeElement StripeElement--empty">
                              <div class="__PrivateStripeElement"
                                   style="margin: 0px !important; padding: 0px !important; border: none !important; display: block !important; background: transparent !important; position: relative !important; opacity: 1 !important;">
                                  <iframe frameborder="0" allowtransparency="true" scrolling="no"
                                          name="__privateStripeFrame5" allowpaymentrequest="true"
                                          src="https://js.stripe.com/v3/elements-inner-card-a6d9e02652f4507c6cbc767fb6e5b802.html#style[base][color]=%2332325d&amp;style[base][fontFamily]=%22Helvetica+Neue%22%2C+Helvetica%2C+sans-serif&amp;style[base][fontSmoothing]=antialiased&amp;style[base][fontSize]=16px&amp;style[base][::placeholder][color]=%23aab7c4&amp;style[invalid][color]=%23fa755a&amp;style[invalid][iconColor]=%23fa755a&amp;componentName=card&amp;wait=false&amp;rtl=false&amp;keyMode=test&amp;apiKey=pk_test_TYooMQauvdEDq54NiTphI7jx&amp;origin=https%3A%2F%2Fstripe.com&amp;referrer=https%3A%2F%2Fstripe.com%2Fdocs%2Fstripe-js&amp;controllerId=__privateStripeController1"
                                          title="Secure payment input frame"
                                          style="border: none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; user-select: none !important; height: 19.2px;"></iframe>
                                  <input class="__PrivateStripeElement-input form-control" aria-hidden="true" aria-label=" "
                                         autocomplete="false" maxlength="1"
                                         style="border: none !important; display: block !important; position: absolute !important; height: 1px !important; top: 0px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent !important; pointer-events: none !important; font-size: 16px !important;">
                              </div>
                          </div>

                          <!-- Used to display form errors. -->
                          <div id="card-errors" role="alert"></div>
                      </div>

                      <button id="stripe-button">Submit Payment</button >
                  </form>
          </div>
          <!--/.Card-->

        </div>

      </div>
      <!--Grid row-->

    </div>

<script>
// Create a Stripe client.
var stripe = Stripe('pk_test_tz0XYRfAEczWzQUDDiYoTdnT00qRLr5p5C');

// Create an instance of Elements.
var elements = stripe.elements();

// Custom styling can be passed to options when creating an Element.
// (Note that this demo uses a wider set of styles than the guide below.)
var style = {
  base: {
    color: '#32325d',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};

// Create an instance of the card Element.
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

// Handle real-time validation errors from the card Element.
card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

// Handle form submission.
var form = document.getElementById('stripe-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

// Submit the form with the token ID.
function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('stripe-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
</script>
{% endblock %}

templates/request-refund.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <title>refund-request</title>
{% endblock %}
{% block content %}
<div class="container">
<div class="row">
    <div class="offset-3 col-6">
        <form method="POST">
            {% csrf_token %}
            {{ rform|crispy }}
            <button class="btn btn-white">Submit</button>
        </form>
    </div>
</div>
</div>
{% endblock %}